#server:
#  port: 8081

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/lab4_kttkpm_quanlychuyenbay_db
#    username: root
#    password: rootpassword
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    properties: 
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#        id:
#          new_generator_mappings: true
#  application:
#    name: tuan08_EurekaClient_APIGateway

eureka:
  client:
    register-with-eureka:
      value: true
    fetch-registry:
      value: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost