server:
  port: 8082 # Port number
spring:
  activemq:
#    broker-url: tcp://0.0.0.0:61616 
    #bỏ localhost
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: false # false = Queue true = Topic

# Self defined queue name
myqueue: boot-activemq-queue