server:
  port: 8081 # Port number
spring:
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: false # false = Queue true = Topic

# Self defined queue name
myqueue: boot-activemq-queue