#link tạo docker-compose.yml: https://www.youtube.com/watch?v=6hMHziv0T2Y

#lệnh chạy duy nhất activemq trong docker: docker run --publish 8161:8161 webcenter/activemq

#link config activemq trong docker-compose.yml: https://github.com/daggerok/spring-boot-rest-jms-activemq/blob/master/spring-jms-docker-activemq/docker-compose.yml

version: "3.8"
services:
  activemq:
    container_name: activemq
    image: webcenter/activemq:latest
    ports:
      # ui
      - "8161:8161"
      # jms
      - "61616:61616"
      #send mess
      - "8082:8082"
    #networks: [backing-services]
    #volumes: ["activemq-data:/opt/activemq/conf", "activemq-data:/data/activemq", "activemq-data:/var/log/activemq"]
    environment:
#      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: "true"
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
#      ACTIVEMQ_STATIC_TOPICS: static-topic-1;static-topic-2
#      ACTIVEMQ_STATIC_QUEUES: static-queue-1;static-queue-2;static-queue-3
      ACTIVEMQ_ENABLED_SCHEDULER: "true"
      ACTIVEMQ_MIN_MEMORY: 512
      ACTIVEMQ_MAX_MEMORY: 2048
      ACTIVEMQ_OPTS: "-Xms2g -Xmx3g"
  ###
  server:
    container_name: qlchuyenbay-server-activemq-docker
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
  ###
  mysqldb:
    #platform: linux/x86_64
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - "3307:3306"
      
    environment:
      MYSQL_DATABASE: kttkpm_qlchuyenbay_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: sapassword
      MYSQL_ROOT_PASSWORD: rootpassword

