#link tạo docker-compose.yml: https://www.youtube.com/watch?v=6hMHziv0T2Y

version: "3.8"
services:
  server:
    container_name: qlchuyenbay-server-activemq-docker
    build: .
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
  mysqldb:
    #platform: linux/x86_64
    container_name: mysqldb
    image: mysql
    restart: always
    ports:
      - "3307:3306"
      
    environment:
      MYSQL_DATABASE: kttkpm_qlchuyenbay_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: sapassword
      MYSQL_ROOT_PASSWORD: rootpassword

